# Generated by Django 3.2.6 on 2021-09-23 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_user', models.CharField(max_length=150)),
                ('receiver_user', models.CharField(max_length=150)),
                ('transferred_value', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('transferred_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
